name: Deploy Firebase-Configured Site to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject Firebase Config and Build
      run: |
        echo "Creating firebase-config.js file..."

        # Create the firebase-config.js file dynamically
        echo "const firebaseConfig = {" > ./firebase-config.js
        echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> ./firebase-config.js
        echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./firebase-config.js
        echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./firebase-config.js
        echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./firebase-config.js
        echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./firebase-config.js
        echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> ./firebase-config.js
        echo "  measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> ./firebase-config.js
        echo "};" >> ./firebase-config.js
        echo "export default firebaseConfig;" >> ./firebase-config.js
        
        echo "Firebase config created successfully."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Assuming your site is ready to be deployed from the root directory
